### ISSUE TITLE
Layout is affected by the size of the monitor and other issues

### ISSUE THREAD

**Issue by ruobinLiu** [UofS-Pulse-Binfo/kp_frontpage#11]
Data part is vertically listed when the frontpage is opened by a smaller monitor. Layout for data part doesn't change on big monitors.

**Comment by laceysanderson** [comment]
The problem specifically, is with the scroll from the top menu bar. When on a smaller monitor with the data part stacked, you click on germplasm and are not scrolled far enough to see the germplasm section.

**Comment by reynoldtan** [comment]
- Provide a section for notification (site maintenance, section downtime etc.)
- When drop down menu launch, element has to be selected to collapse.
- Layout is not centered on reduced screen size.
- Link to Tripal HQ in user control panel.

**Comment by laceysanderson** [comment]
Live on KP!
