### ISSUE TITLE
Add KnowPulse Overview and Knowledge-based Help

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/kp_frontpage#17]
Update frontpage to show KnowPulse overview (sales/landing page) and knowledge-based help (orientation page) pages.
1. Update context menu to include a links to pages.
2. Register a page address using hook_menu().

![Screen Shot 2020-11-24 at 2 51 27 PM](https://user-images.githubusercontent.com/15472253/100150156-d6c87200-2e64-11eb-8d43-0b908b6e1980.png)

**Comment by laceysanderson** [comment]
Completed. PR Merged!
