### ISSUE TITLE
Simplify layout

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/kp_frontpage#9]
Simplify frontend to address issues such as site being complicated, information not apparent and overall layout is overwhelming. This proposed layout focuses on Crops, Tools and Data. Additional sections such as news and events, are relocated towards the 2nd fold of layout.

![kp3](https://user-images.githubusercontent.com/15472253/64047478-1f8f5f00-cb2c-11e9-85ea-346d7518bec4.jpg)

**Comment by laceysanderson** [comment]
Live!
